
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action actionAction;
	
	private global::Gtk.Action connectAction1;
	
	private global::Gtk.Action helpAction;
	
	private global::Gtk.Action connectAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar5;
	
	private global::Gtk.Toolbar toolbar2;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Statusbar statusbar6;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.actionAction = new global::Gtk.Action ("actionAction", global::Mono.Unix.Catalog.GetString ("action"), null, null);
		this.actionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("action");
		w1.Add (this.actionAction, null);
		this.connectAction1 = new global::Gtk.Action ("connectAction1", null, global::Mono.Unix.Catalog.GetString ("Will connect to DOPs server - allowing cloud chat administrator to communicate with cloud chat managers and cloudchat clients"), "gtk-connect");
		this.connectAction1.IsImportant = true;
		w1.Add (this.connectAction1, "F8");
		this.helpAction = new global::Gtk.Action ("helpAction", null, null, "gtk-help");
		w1.Add (this.helpAction, null);
		this.connectAction = new global::Gtk.Action ("connectAction", null, null, "gtk-connect");
		w1.Add (this.connectAction, "F8");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("cloudchatAdministratorTEST");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar5'/></ui>");
		this.menubar5 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar5")));
		this.menubar5.Name = "menubar5";
		this.vbox1.Add (this.menubar5);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar5]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='connectAction1' action='connectAction1'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.vbox1.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbar6 = new global::Gtk.Statusbar ();
		this.statusbar6.Name = "statusbar6";
		this.statusbar6.Spacing = 6;
		this.vbox2.Add (this.statusbar6);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar6]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w5.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 825;
		this.DefaultHeight = 473;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.connectAction1.Activated += new global::System.EventHandler (this.OnConnectActionActivated);
		this.helpAction.Activated += new global::System.EventHandler (this.OnHelpActionActivated);
		this.connectAction.Activated += new global::System.EventHandler (this.OnConnectActionActivated);
	}
}
