
function insertWidget(id,src,startfnc)
{
	str1 = "<div id=\""+id+"\"></div>";
	str2 = "<script type=\"text/JavaScript\" src=\""+src+"\"></script>";
	str3 = "<script type=\"text/JavaScript\"> "+startfnc+" </script>";
	document.write(str1);
	document.write(str2); 
    	document.write(str3);
}

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000)
               .toString(16)
               .substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
         s4() + '-' + s4() + s4() + s4();
}

function dingdong()
{
    if(/loaded|complete/.test(document.readyState))
        $('#connectBtn').click();    
}

function getURLParameter(name) {
  return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search)||[,""])[1].replace(/\+/g, '%20'))||null
}

// clientID must be autogenerated, since more than one guest could be visiting the homepage
function insertChatWidget(homepageAlias,managerID,urlManagerImg, ypxpos,xpxpos, title)
{
	
category = getURLParameter('category');managerid = getURLParameter('managerid');if(managerid==""){managerid="DADER2D26BAA30E8AD733671370FECFC"};imageurl = getURLParameter('imageurl');if(imageurl == null){imageurl="http://cloudchatmanager.com/CloudChatManager/images/"};ypos = getURLParameter('ypos');if(ypos == null){ypos = 0};xpos = getURLParameter('xpos');if(xpos == null){xpos = 0};

	if(ypos !== null || xpos !== null) {
		ypxpos = ypos;
		xpxpos = xpos;
	}
	if(managerID == "")
		managerID = managerid;
	if(homepageAlias=="")
		homepageAlias=category;
	var strUrlManager = "REMOTE";
	if(imageurl !== null)
		urlManagerImg = imageurl;
	if(urlManagerImg == "LOCAL") // used when testing local, then write LOCL in urlManagerImg parameter - client will then login to localhost server
	{
		strUrlManager = "LOCAL";
		urlManagerImg = "";
	}
	else {
		strUrlManager = "REMOTE";
		if(imageurl == null)
			urlManagerImg = "http://cloudchatmanager.com/CloudChatManager/images/"
	}
        clientID = guid();
        var stringAliasClientID = clientID;
        stringAliasClientID = stringAliasClientID.substr(0,8); // only first 8 characters should be shown
	strJquery1 = "<script src=\"js/jquery.js\"></script>"; // <!-- IMPORTANT it must be version jQuery v1.7.2 jquery.com -->
	strJquery2 = "<script src=\"js/move.min.js\"></script>";

	strWindowSize = "<script>curtain_size=1;curtain_right=\"off\";screenwidth=0;screenheight = 0;screenwidth  = $(window).width();screenheight = $(window).height();</script>";
	strCompression = "<script src=\"../../DataEncoderDecoder/compression-lib/compression.js\"></script>";
	strDataEncoder = "<script src=\"../../DataEncoderDecoder/dataencoderdecoder.js\"></script>";
	strSocketAPI = "<script src=\"../../socketserverAPI/socketserverAPI.js\"></script>";
	strComponentLogin = "<script src=\"js/mvc-login-widgetclient.js\"></script>";
	strComponentChat = "<script src=\"js/mvc-chat-widgetclient.js\"></script>";
	strList = "<script src=\"js/list.js\"></script>";
	strbootstrapcss1 = "<link rel=\"stylesheet\" href=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\"  rel=\"stylesheet\" media=\"screen\">";
	strbootstrapcss2 = "<link rel=\"stylesheet\" href=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css\"  rel=\"stylesheet\" media=\"screen\">";
	strbootstrapjs = "<script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js\"></script>";
	str1 = "<div  class=\"imageoverlap\" id=\"right-pane\" style=\"padding:0px;\" >";
	str2 = "<div class=\"sandbox\"  >";
	str3 = "<div class=\"right-pane box\" id=\"rightpanebox\" style=\"padding:0px;\">";
	str4 = "<script type=\"text/javascript\">";
	str5 = "function RightpaneWidgetCallback(JSONobject) {";
	str6 = "var wRightpaneJSON = JSONobject[0];";
	str7 = "}";
	str8 = "insertWidget(\"RightpaneWidget\",\"Widgets/RightPaneWidget/bootstrap_rightpane_widget.js\",\"init_rightpane("+ypxpos+","+xpxpos+",\\\""+title+"\\\");\");";
	str9 = "</script>";
	str10 = "</div>";
	str11 = "</div>";
	str12 = "</div>";
	str13 = "<script src=\"js/xui.js\" type=\"application/javascript\" charset=\"utf-8\"></script>";
	str14 = "<script src=\"js/xui.swipe.js\" type=\"application/javascript\" charset=\"utf-8\"></script>";
	str15 = "<script> $(window).resize(function () { document.getElementById('chat_session').style.top = "+ ypxpos +"+ 'px'; document.getElementById('chat_session').style.left = "+xpxpos+"+ 'px'; });</script>";
        strLoginHiddenSection = "<div > <input class=\"hidden\" type=\"text\" size=\"32\" id=\"destination_address\" value=\""+managerID+"\" /> \
            <button id=\"connectBtn\"  class=\"hidden btn btn-default btn-block serverconnect\" > connect with server </button></div> \
            <div class=\"hidden\"> \
                <input type=\"text\" placeholder=\"REMOTE\" id=\"wsUri\" value=\""+strUrlManager+"\" > \
            </div> \
            <div class=\"hidden\"> \
                <input type=\"text\" placeholder=\"uniqueId\" id=\"uniqueId\" value=\""+clientID+"\"> \
            </div> \
            <div class=\"hidden\"> \
                <input type=\"text\" placeholder=\"homepageAlias\" id=\"homepageAlias\" value=\""+homepageAlias+"\"> \
            </div> \
            <div class=\"hidden\"> \
                <input type=\"text\" placeholder=\"urlManagerImg\" id=\"urlManagerImg\" value=\""+urlManagerImg+"\"> \
            </div> \
            <div class=\"hidden\"> \
                 <input type=\"text\" placeholder=\"Username\" id=\"username\" value=\"user_"+stringAliasClientID+"\"> \
            </div> \
            <div class=\"hidden\"> \
                 <input type=\"password\" placeholder=\"Password\" id=\"password\" value=\"12345678\"> \
            </div>";
        strWindowReady = "<script type=\"text/javascript\"> $(window).ready(function() { $('input').bind('focus', function() { $('#connectBtn').click();  $('#chatarea').scrollTop($('#chatarea')[0].scrollHeight);  })  }); </script>";

        

	document.write(strJquery1);
	document.write(strJquery2);
	document.write(strWindowSize);
	document.write(strCompression);
	document.write(strDataEncoder);
	document.write(strSocketAPI);
	document.write(strComponentLogin);
	document.write(strComponentChat);
	document.write(strList);
	document.write(strbootstrapcss1);
	document.write(strbootstrapcss2);
	document.write(strbootstrapjs);
	document.write(str1);
	document.write(str2);
	document.write(str3);
	document.write(str4);
	document.write(str5);
	document.write(str6);
	document.write(str7);
	document.write(str8);
	document.write(str9);
	document.write(str10);
	document.write(str11);
	document.write(str12);
	document.write(str13);
	document.write(str14);
	document.write(str15);
        document.write(strLoginHiddenSection);
        document.write(strWindowReady);
        
        dingdong();
}

function ChatWidget()
{
	// this will force it to get its parameters from the URL
	insertChatWidget("","","",0,0,"Chat");
}

//function hide_panes(upper, left, right, lower)
//{
//	if(right==true)	hide_rightpane();
//}

   

var _timer_startup=setInterval(function(){
if(/loaded|complete/.test(document.readyState)){
  clearInterval(_timer_startup);
  dingdong();
}
}, 3);






